title: RE-blog
name: hazouka
description: Reverse Engineering notes and writeups
url: "https://hazouka.github.io"
baseurl: ""

permalink: /:title/

include:
  - _pages

plugins: []

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
